name: HomeWarpGUI
version: ${project.version}
main: com.jaaakee.homewarpgui.HomeWarpGUI
api-version: 1.13
authors: [Jaaakee]
description: Homes and Warps in a GUI

commands:
  home:
    description: Opens Home GUI or Teleport to Home
    usage: /home or /home <name>
  warp:
    description: Opens Warp GUI or Teleport to Warp
    usage: /warp or /warp <name>